version: "3.7"

services:
  vscode:
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - ../:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.ssh:/mnt/ssh
      - ~/.zsh_history:/home/developer/.zsh_history
      - ~/.gitconfig:/home/developer/.initial_gitconfig
    environment:
      - TZ=
    entrypoint: ["zsh", "-c", "while sleep 1000; do :; done"]